// Package main implements a code generator that creates Reset() methods
// for structs annotated with the "// generate:reset" comment.
//
// # Usage
//
//	go run ./cmd/reset [root-dir]
//
// If root-dir is not provided, the generator locates the module root by
// searching upward for go.mod and scans all packages from there.
//
// For each struct directly preceded by the comment "// generate:reset" the
// generator emits a Reset() method into reset.gen.go in the same package
// directory.  The generated file is formatted with go/format and carries a
// "DO NOT EDIT" header so other tooling (and the noexit analyser) treats it
// as auto-generated.
//
// # Reset rules
//
// The Reset() method sets every exported and unexported field to its zero
// value, applying the following type-specific rules:
//
//   - Primitive types (bool, numeric, string): assigned their literal zero
//     value (false, 0, "").
//   - Slice fields: truncated to length 0 while preserving capacity:
//     s = s[:0].
//   - Map fields: cleared with the built-in clear() function (no-op on nil).
//   - Named types / selector-qualified types (e.g. pkg.Type): if the value
//     implements interface{ Reset() } at runtime, that method is called.
//   - Pointer fields: guarded by a nil check; the dereferenced value is then
//     reset according to these rules.  For pointers to named types the
//     pointer itself is checked via a type assertion so pointer-receiver
//     Reset() methods are discovered correctly.
//   - Interface, function, and channel fields: set to nil.
//   - Fixed-size array fields: skipped (no universally correct reset rule).
//
// # Generated code example
//
// Given the following annotated struct in package example:
//
//	// generate:reset
//	type Stats struct {
//	    count   int
//	    label   string
//	    samples []float64
//	    index   map[string]int
//	}
//
// The generator produces reset.gen.go:
//
//	// Code generated by cmd/reset. DO NOT EDIT.
//
//	package example
//
//	func (s *Stats) Reset() {
//	    if s == nil {
//	        return
//	    }
//	    s.count = 0
//	    s.label = ""
//	    s.samples = s.samples[:0]
//	    clear(s.index)
//	}
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
)

const (
	triggerComment = "generate:reset"
	outputFile     = "reset.gen.go"
)

func main() {
	root := scanRoot()
	if err := generate(root); err != nil {
		log.Fatal(err)
	}
}

// scanRoot returns the directory to scan: the first CLI argument, or the
// module root located by searching upward for go.mod from the working dir.
func scanRoot() string {
	if len(os.Args) > 1 {
		return os.Args[1]
	}
	root, err := moduleRoot(".")
	if err != nil {
		log.Fatalf("finding module root: %v", err)
	}
	return root
}

// moduleRoot walks up the directory tree until it finds go.mod.
func moduleRoot(start string) (string, error) {
	abs, err := filepath.Abs(start)
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(abs, "go.mod")); err == nil {
			return abs, nil
		}
		parent := filepath.Dir(abs)
		if parent == abs {
			return "", fmt.Errorf("go.mod not found")
		}
		abs = parent
	}
}

// generate walks all subdirectories under root and processes each Go package.
func generate(root string) error {
	return filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if !info.IsDir() {
			return nil
		}
		name := info.Name()
		if strings.HasPrefix(name, ".") || name == "vendor" || name == "testdata" {
			return filepath.SkipDir
		}
		return processPackage(path)
	})
}

// structDef collects the data needed to render one Reset() method.
type structDef struct {
	name   string
	fields []*fieldDef
}

type fieldDef struct {
	typ  ast.Expr // interface first: reduces GC pointer span (fieldalignment)
	name string
}

// processPackage parses all non-test, non-generated Go files in dir, finds
// annotated structs, and writes (or removes) reset.gen.go.
//
// Files are parsed individually with parser.ParseFile to avoid the deprecated
// parser.ParseDir (deprecated in Go 1.25).
func processPackage(dir string) error {
	pkgName, files, err := parseGoFiles(dir)
	if err != nil || len(files) == 0 {
		return nil // not a Go package — skip silently
	}

	var defs []structDef
	for _, file := range files {
		defs = append(defs, collectStructs(file)...)
	}

	outPath := filepath.Join(dir, outputFile)

	if len(defs) == 0 {
		// Remove stale generated file if it exists.
		_ = os.Remove(outPath)
		return nil
	}

	src, err := renderFile(pkgName, defs)
	if err != nil {
		return fmt.Errorf("render %s: %w", dir, err)
	}
	if err := os.WriteFile(outPath, src, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", outPath, err)
	}
	fmt.Printf("wrote %s (%d struct(s))\n", outPath, len(defs))
	return nil
}

// parseGoFiles reads and parses all non-test, non-generated .go files in dir.
// Returns the package name and the parsed AST files.
func parseGoFiles(dir string) (string, []*ast.File, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return "", nil, err
	}

	fset := token.NewFileSet()
	var files []*ast.File
	var pkgName string

	for _, e := range entries {
		n := e.Name()
		if e.IsDir() || !strings.HasSuffix(n, ".go") ||
			strings.HasSuffix(n, "_test.go") || n == outputFile {
			continue
		}
		f, err := parser.ParseFile(fset, filepath.Join(dir, n), nil, parser.ParseComments)
		if err != nil {
			continue
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		} else if f.Name.Name != pkgName {
			continue // skip files from a different package in the same dir
		}
		files = append(files, f)
	}
	return pkgName, files, nil
}

// collectStructs returns all structs in file annotated with // generate:reset.
func collectStructs(file *ast.File) []structDef {
	var result []structDef

	for _, decl := range file.Decls {
		genDecl, ok := decl.(*ast.GenDecl)
		if !ok {
			continue
		}

		for _, spec := range genDecl.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}

			// Check the trigger comment on both the GenDecl and the TypeSpec
			// (the latter appears inside parenthesised type blocks).
			if !hasTrigger(genDecl.Doc) && !hasTrigger(ts.Doc) {
				continue
			}

			sd := structDef{name: ts.Name.Name}
			for _, f := range st.Fields.List {
				if len(f.Names) == 0 {
					// Embedded field: use the type expression as the field name.
					if name := embeddedName(f.Type); name != "" {
						sd.fields = append(sd.fields, &fieldDef{name: name, typ: f.Type})
					}
					continue
				}
				for _, ident := range f.Names {
					sd.fields = append(sd.fields, &fieldDef{name: ident.Name, typ: f.Type})
				}
			}
			result = append(result, sd)
		}
	}
	return result
}

// hasTrigger reports whether doc contains the exact comment "// generate:reset".
func hasTrigger(doc *ast.CommentGroup) bool {
	if doc == nil {
		return false
	}
	for _, c := range doc.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == triggerComment {
			return true
		}
	}
	return false
}

// embeddedName returns the simple type name of an embedded field.
func embeddedName(e ast.Expr) string {
	switch t := e.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return t.Sel.Name
	case *ast.StarExpr:
		return embeddedName(t.X)
	}
	return ""
}

// renderFile produces the formatted source bytes for reset.gen.go.
func renderFile(pkgName string, defs []structDef) ([]byte, error) {
	var buf bytes.Buffer
	fmt.Fprintf(&buf, "// Code generated by cmd/reset. DO NOT EDIT.\n\n")
	fmt.Fprintf(&buf, "package %s\n\n", pkgName)

	for i := range defs {
		renderReset(&buf, &defs[i])
	}

	return format.Source(buf.Bytes())
}

// renderReset writes the Reset() method for s into buf.
func renderReset(buf *bytes.Buffer, s *structDef) {
	recv := strings.ToLower(string(s.name[0]))
	fmt.Fprintf(buf, "func (%s *%s) Reset() {\n", recv, s.name)
	fmt.Fprintf(buf, "if %s == nil {\nreturn\n}\n", recv)

	for _, f := range s.fields {
		if f.name == "" {
			continue
		}
		expr := recv + "." + f.name
		writeFieldReset(buf, expr, f.typ, 1)
	}

	fmt.Fprintf(buf, "}\n\n")
}

// tabs returns n tab characters.
func tabs(n int) string { return strings.Repeat("\t", n) }

// writeFieldReset emits the reset statement(s) for a single field expression.
func writeFieldReset(buf *bytes.Buffer, expr string, typ ast.Expr, depth int) {
	tab := tabs(depth)

	switch t := typ.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero(t.Name); ok {
			fmt.Fprintf(buf, "%s%s = %s\n", tab, expr, zero)
		} else {
			// Named type — check at runtime whether it implements Reset().
			fmt.Fprintf(buf, "%sif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", tab, expr)
			fmt.Fprintf(buf, "%s\tresetter.Reset()\n%s}\n", tab, tab)
		}

	case *ast.StarExpr:
		// Pointer: nil-guard, then reset the pointed-to value.
		fmt.Fprintf(buf, "%sif %s != nil {\n", tab, expr)
		writePtrInner(buf, expr, t.X, depth+1)
		fmt.Fprintf(buf, "%s}\n", tab)

	case *ast.ArrayType:
		if t.Len == nil {
			// Slice: truncate, preserve capacity.
			fmt.Fprintf(buf, "%s%s = %s[:0]\n", tab, expr, expr)
		}
		// Fixed-size arrays: no universally safe reset — skip.

	case *ast.MapType:
		// clear() is a no-op on nil maps.
		fmt.Fprintf(buf, "%sclear(%s)\n", tab, expr)

	case *ast.SelectorExpr:
		// Qualified type (e.g. time.Time) — runtime Reset() check.
		fmt.Fprintf(buf, "%sif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", tab, expr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n%s}\n", tab, tab)

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		fmt.Fprintf(buf, "%s%s = nil\n", tab, expr)
	}
}

// writePtrInner emits the reset for the value a non-nil pointer points to.
// ptrExpr is the pointer expression (already confirmed non-nil by the caller).
func writePtrInner(buf *bytes.Buffer, ptrExpr string, inner ast.Expr, depth int) {
	tab := tabs(depth)

	switch t := inner.(type) {
	case *ast.Ident:
		if zero, ok := primitiveZero(t.Name); ok {
			// *primitive: dereference and assign zero value.
			fmt.Fprintf(buf, "%s*%s = %s\n", tab, ptrExpr, zero)
		} else {
			// *struct: use the pointer itself for the type assertion so that
			// pointer-receiver Reset() methods are discovered.
			fmt.Fprintf(buf, "%sif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", tab, ptrExpr)
			fmt.Fprintf(buf, "%s\tresetter.Reset()\n%s}\n", tab, tab)
		}

	case *ast.SelectorExpr:
		// *pkg.Type: same pointer-assertion approach.
		fmt.Fprintf(buf, "%sif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", tab, ptrExpr)
		fmt.Fprintf(buf, "%s\tresetter.Reset()\n%s}\n", tab, tab)

	case *ast.ArrayType:
		if t.Len == nil {
			// *[]T: dereference and truncate.
			fmt.Fprintf(buf, "%s*%s = (*%s)[:0]\n", tab, ptrExpr, ptrExpr)
		}

	case *ast.MapType:
		// *map: dereference and clear.
		fmt.Fprintf(buf, "%sclear(*%s)\n", tab, ptrExpr)

	case *ast.StarExpr:
		// **T: nil the inner pointer.
		fmt.Fprintf(buf, "%s*%s = nil\n", tab, ptrExpr)

	case *ast.InterfaceType, *ast.FuncType, *ast.ChanType:
		fmt.Fprintf(buf, "%s*%s = nil\n", tab, ptrExpr)
	}
}

// primitiveZero returns the Go literal zero value for built-in primitive types.
func primitiveZero(name string) (string, bool) {
	switch name {
	case "bool":
		return "false", true
	case "string":
		return `""`, true
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64",
		"uintptr", "byte", "rune",
		"float32", "float64",
		"complex64", "complex128":
		return "0", true
	}
	return "", false
}
